# Generated by Django 2.2.3 on 2019-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hantorism_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentNum',
            field=models.CharField(max_length=10),
        ),
    ]
