# Generated by Django 2.2.3 on 2019-08-02 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_hantorism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_rent_state', models.BooleanField(default=False)),
                ('rent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_owner_name', models.CharField(max_length=20)),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_hantorism.HantorismUser')),
            ],
        ),
    ]
